# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170614_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answers',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
