# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_auto_20170616_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answers',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='Answer_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
