# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
