# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPage', '0002_details_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profilePic',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]

